### ISSUE TITLE
[Bug]: Not able to use Mobilenet V3 as a backbone for CFlow despite being used in paper

### ISSUE THREAD

**Issue by j99ca** [openvinotoolkit/anomalib#1442]
### Describe the bug

The [CFlow paper](https://arxiv.org/pdf/2107.12571.pdf) uses resnet variants as well as Mobilenet V3 as backbones. However, anomalib does not appear to work when trying to change the backbone to Mobilenet v3. I tried changing the backbone to the timm feature extractor "mobilenetv3_large_100" but no configuration of the layers (blocks) seems to work. It appears to be tied to how the layers are exposed for resnet and how mobilenet v3 uses blocks in the timm feature extraction implementation.

There is an issue [logged here](https://github.com/openvinotoolkit/anomalib/issues/1144) that has displayed similar problems

### Dataset

N/A

### Model

CFlow

### Steps to reproduce the behavior

create a yaml config containing "mobilenetv3_large_100" as the backbone. Try various forms of blocks (e.g. "blocks", "blocks.x.y") in the layers.

### OS information

OS information:
- OS: Ubuntu 22.04
- Python version: 3.8
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

The paper of CFlow has shown good results with MobilenetV3. Ideally this would work and allow a much smaller model that can run faster on limited hardware

### Pip/GitHub

pip

### Configuration YAML

```yaml
N/A
```

### Logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blaz-r** [comment]
Looking at the structure of MobilenetV3, it seems like you can't directly access layers as in ResNet:
![image](https://github.com/openvinotoolkit/anomalib/assets/61357777/156294d4-2fa0-4966-834a-2e63f2189b85)
so in code one would need to do features.blocks[index], but currently the feature extractor expects layer names to exactly match:
https://github.com/openvinotoolkit/anomalib/blob/66532fc1625020ce7ff6f3fc1565663aa540e834/src/anomalib/models/components/feature_extractors/timm.py#L89-L97
so this code is incompatible.
To make this work, something like FastFlow implementation would need to be used I think:
https://github.com/openvinotoolkit/anomalib/blob/66532fc1625020ce7ff6f3fc1565663aa540e834/src/anomalib/models/fastflow/torch_model.py#L125-L128
and then:
https://github.com/openvinotoolkit/anomalib/blob/66532fc1625020ce7ff6f3fc1565663aa540e834/src/anomalib/models/fastflow/torch_model.py#L222-L241
but I assume in case of MobilenetV3 it can be simpler, we could just make feature extractor return blocks, then index those to get the desired indices.

---

A temporary fix would be to replace encoder and pool_dims in cflow torch model with the following:
```python
self.encoder = timm.create_model(backbone, pretrained=pre_trained, features_only=True, exportable=True, out_indices=layers)
self.pool_dims = self.encoder.feature_info.channels()
self.pool_layers = list(range(len(layers))) # since the returned features are now a list, we index them from 0 to len(layers)
```
and then in config use indices instead of names, so for block 1 you'd write 1 and so on, like this:
```yaml
  backbone: mobilenetv3_large_100
  pre_trained: true
  layers:
    - 1
    - 2
    - 3
```

I think we should have a more general solution for this, but I'm not sure if I'm missing something or feature extractor would need a refactor to support this @ashwinvaidya17 @samet-akcay ?

**Comment by blaz-r** [comment]
Looking at this implementation, I believe a general fix would be to change the function that maps layer to index. Current implementation with offset and indexing is not that general. 

I do see that there is a warning that this will be removed in future, but I found the following way that can make this more general:
Calling `net.feature_info.info` gives a list of dicts, where names of returned features are present inside "module" key:
```python
mobile = timm.create_model("mobilenetv3_large_100", pretrained=False, features_only=True, exportable=True)
rn18 = timm.create_model("resnet18", pretrained=False, features_only=True, exportable=True)
wrn50 = timm.create_model("wide_resnet50_2", pretrained=False, features_only=True, exportable=True)

print(mobile.feature_info.info)
print(rn18.feature_info.info)
print(wrn50.feature_info.info)
```
gives:
```python
[{'stage': 1, 'reduction': 2, 'module': 'blocks.0.0', 'hook_type': '', 'num_chs': 16}, {'stage': 2, 'reduction': 4, 'module': 'blocks.1.1', 'hook_type': '', 'num_chs': 24}, {'stage': 3, 'reduction': 8, 'module': 'blocks.2.2', 'hook_type': '', 'num_chs': 40}, {'stage': 5, 'reduction': 16, 'module': 'blocks.4.1', 'hook_type': '', 'num_chs': 112}, {'stage': 7, 'reduction': 32, 'module': 'blocks.6.0', 'hook_type': '', 'num_chs': 960}]
[{'num_chs': 64, 'reduction': 2, 'module': 'act1'}, {'num_chs': 64, 'reduction': 4, 'module': 'layer1'}, {'num_chs': 128, 'reduction': 8, 'module': 'layer2'}, {'num_chs': 256, 'reduction': 16, 'module': 'layer3'}, {'num_chs': 512, 'reduction': 32, 'module': 'layer4'}]
[{'num_chs': 64, 'reduction': 2, 'module': 'act1'}, {'num_chs': 256, 'reduction': 4, 'module': 'layer1'}, {'num_chs': 512, 'reduction': 8, 'module': 'layer2'}, {'num_chs': 1024, 'reduction': 16, 'module': 'layer3'}, {'num_chs': 2048, 'reduction': 32, 'module': 'layer4'}]
```
we could then simply get the index where module contains the specified layer. That works for all case, whether that is `layer1` or `block.1.1`, which are the features we want to access, even if they reside inside `blocks` submodule.

With current approach, this offset bit is not really general, and additionally we do the following to get layer names:
```python
print(list(dict(mobile.named_children()).keys()))
print(list(dict(rn18.named_children()).keys()))
print(list(dict(wrn50.named_children()).keys()))
```
giving us:
```python
['conv_stem', 'bn1', 'act1', 'blocks']
['conv1', 'bn1', 'act1', 'maxpool', 'layer1', 'layer2', 'layer3', 'layer4']
['conv1', 'bn1', 'act1', 'maxpool', 'layer1', 'layer2', 'layer3', 'layer4']
```
It is obvious that while it works for resnets, it doesn't work for mobilenet, as features are actually parts of `blocks`.

**Comment by blaz-r** [comment]
This is now addressed in #1443. I do think that we should also update the docs regarding backbone info.

**Comment by j99ca** [comment]
@blaz-r very nice! What would the layers in the .yaml file look like for either resnet18 or mobilenetv3_large_100 with this change?

**Comment by blaz-r** [comment]
You can use the following code to print the available layers:
```python
model = timm.create_model("mobilenetv3_large_100", pretrained=False, features_only=True, exportable=True)
print([info["module"] for info in model.feature_info.info])
```
where you replace the model string with desired net.
For `mobilenetv3_large_100` the results are:
```
['blocks.0.0', 'blocks.1.1', 'blocks.2.2', 'blocks.4.1', 'blocks.6.0']
```
and for `resnet18`:
```
['act1', 'layer1', 'layer2', 'layer3', 'layer4']
```
I also changed the code to print warning with all layers in case wrong one is provided, so you can be sure.
