### ISSUE TITLE
🔨 Add default metric values to `Engine`

### ISSUE THREAD

**Issue by MartinPernus** [openvinotoolkit/anomalib#1747]
### Describe the bug

001_getting_started.ipynb includes the following code to validatate the model:
```
# load best model from checkpoint before evaluating
test_results = engine.test(
    model=model,
    datamodule=datamodule,
    ckpt_path=engine.trainer.checkpoint_callback.best_model_path,
)
```
Printing the `test_results`variable shows that it is empty (`[{}]`).

I have manually checked that the model in question (PaDiM) returns dictionary as part of its Lightning test step. The test step equals to `validation_step` function in the model with 

```
batch["anomaly_maps"] = self.model(batch["image"])
return batch
```
I am not sure where this information gets later lost.

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

1. Clone this repo
2. Install anomalib from source using `pip install -e .`, followed by `pip install -e .[full]`.
3. Run notebook "notebooks/001_getting_started.py"

### OS information

OS information:
- OS: macOS and Ubuntu
- Python version: 3.10
- Anomalib version: newest

### Expected behavior

I would expect to see test results either in form of anomaly maps or in form of some metrics already calculated based on the ground truth data. 

### Pip/GitHub

GitHub

### What version/branch did you use?

Newest

### Configuration YAML

```yaml
N/A
```

### Logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@MartinPernus, this is because, `Engine` in the notebook does not provide any metrics to compute. `Engine.test()` returns test_metrics. Since there is nothing to compute, `test_results` becomes an empty dictionary. 

I'll modify this notebook as the following:
- Add default metrics to `Engine` to compute
- Explain that `Engine.test` returns a test-metric, not predictions. 
- Predictions can be done by `Engine.predict`
