### ISSUE TITLE
The number of epoch

### ISSUE THREAD

**Issue by mouxinyue1** [openvinotoolkit/anomalib#303]
Hello, I would like to ask why the epoch is 1 by default? Will adding epoch improve detection performance?

**Comment by djdameln** [comment]
Hi, the default number of epochs depends on the type of algorithm. Feature extraction based methods such as Padim and PatchCore require only a single epoch, because the weights of the convolutional backbone are fixed. These methods rely on pre-trained feature extractors to obtain a feature representation for each image, and then use statistical methods to create a normality model on top of the extracted features. No fine-tuning of the neural network weights is involved when these models are trained, so increasing the number of epochs will be ineffective.

Other algorithms, such as STFPM, do require fine-tuning of the neural network weights, so you will see that for those models the default number of epochs is higher.

More information about each of the individual algorithms can be found in the readme files in the root directory of each of the model implementations, e.g. 

Padim: https://github.com/openvinotoolkit/anomalib/tree/development/anomalib/models/padim
STFPM: https://github.com/openvinotoolkit/anomalib/tree/development/anomalib/models/stfpm

**Comment by mouxinyue1** [comment]
Thank you very much for your answer

**Comment by djdameln** [comment]
No problem! I will be closing this issue now. Feel free to re-open if anything is still unclear

**Comment by dq2b25** [comment]
> Hi, the default number of epochs depends on the type of algorithm. Feature extraction based methods such as Padim and PatchCore require only a single epoch, because the weights of the convolutional backbone are fixed. These methods rely on pre-trained feature extractors to obtain a feature representation for each image, and then use statistical methods to create a normality model on top of the extracted features. No fine-tuning of the neural network weights is involved when these models are trained, so increasing the number of epochs will be ineffective.
> 
> Other algorithms, such as STFPM, do require fine-tuning of the neural network weights, so you will see that for those models the default number of epochs is higher.
> 
> More information about each of the individual algorithms can be found in the readme files in the root directory of each of the model implementations, e.g.
> 
> Padim: https://github.com/openvinotoolkit/anomalib/tree/development/anomalib/models/padim STFPM: https://github.com/openvinotoolkit/anomalib/tree/development/anomalib/models/stfpm

If I use RandomHorizontalFlip, RandomVerticalFlip, RandomAffine to augment Images, then Padim need more epochs.
