### ISSUE TITLE
The library not working after changes.

### ISSUE THREAD

**Issue by shrinand1996** [openvinotoolkit/anomalib#356]
**Describe the bug**
I have used this library in the past and had no issues when training on mvtec dataset. But i tried again after a month, using the same code, and it throws errors. When i hit train, there is an error relating to get_configurable_parameters and omegaconf.errors.ConfigAttributeError: Missing key threshold.
I am using google colab.
**To Reproduce**
1. set dataset directory path in the config file of padim
2. run python3 tools/train.py 

**Expected behavior**
As earlier, it should work without any problems and the training should be uninterrupted.  it would have been better if the error was more concise.

**Screenshots**
- If applicable, add screenshots to help explain your problem.

**Hardware and Software Configuration**
google colab

**Additional context**
Traceback (most recent call last):
  File "tools/train.py", line 99, in <module>
    train()
  File "tools/train.py", line 67, in train
    config = get_configurable_parameters(model_name=args.model, config_path=args.config)
  File "/usr/local/lib/python3.7/dist-packages/anomalib/config/config.py", line 167, in get_configurable_parameters
    if "pixel_default" not in config.model.threshold.keys():
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py", line 358, in __getattr__
    key=key, value=None, cause=e, type_override=ConfigAttributeError
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/base.py", line 237, in _format_and_raise
    type_override=type_override,
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py", line 873, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py", line 354, in __getattr__
    key=key, default_value=_DEFAULT_MARKER_, validate_key=False
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py", line 445, in _get_impl
    key=key, throw_on_missing_key=True, validate_key=validate_key
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py", line 78, in _get_child
    throw_on_missing_key=throw_on_missing_key,
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py", line 482, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key threshold
    full_key: model.threshold
    object_type=dict

**Comment by djdameln** [comment]
Thanks for reporting this. We recently made some [changes](https://github.com/openvinotoolkit/anomalib/pull/328/files) to the way in which the performance metrics and adaptive threshold are configured and initialized. The anomaly score threshold settings have been moved from the `model` section to the `metrics` section of the config. You could have a look at our most recent [default padim config file](https://github.com/openvinotoolkit/anomalib/blob/development/anomalib/models/padim/config.yaml) for an example.

The most recent release (v0.3.1) does not include these changes yet, so there is a mismatch between the config file on the latest development branch and the pypi package. I suspect that your problems are caused by this mismatch. A new release is scheduled for this week, which will include the new metrics/thresholding configuration and make the config.yaml and the pypi package up to date again.

In the mean time, you could check out the release of the version of anomalib that you have installed in your environment, e.g.:
```
git checkout v.0.3.1
```
This will make sure that the model folders on your system contain the `config.yaml` files compatible with the anomalib version in your environment. Please let us know if this solves your problem.

**Comment by shrinand1996** [comment]
Yes, i figured. So instead i tried it with v 0.3.0 and cloned an old repo. Worked without issues. 
Looking forward to the changes and final push!!
