### ISSUE TITLE
PatchCore only support 224x224 input, and 28x28 feature maps.

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#40]

**Comment by soad89** [comment]
Hello, can you please guide me a bit what needs to be modified to allow higher input resolutions?
Thanks

**Comment by Lucas-Steinmann** [comment]
Hi,
I solved this problem by inferring the largest feature map size from the given feature layer names and the input/tiling size.
I assumed 

 * the layer names to be of the same format as ResNet ("layer1", "layer2", ...) and
 * the sub-sampling ratios are the same as in ResNet, i.e. `2**(1+layer_num)`

I know this is kind of hard-coded, but if that is general enough for the maintainers of anomalib, then I'm happy to create a pull request.
Support for other backbones of torchvision could be added by someone motivated enough, to collect all output shapes of various backbones.

More general solutions would either require:

 * forwarding a blank image and collecting the feature maps, to get their sizes, or
 * inspecting the network to infer the output shapes/sub-sampling ratio. But this is difficult, since the network implementation of torchvision, does not keep track of the output shapes explicitly. Some other libraries (e.g. detectron2 with their `ShapeSpec`) do this.

**Comment by samet-akcay** [comment]
Hi @Lucas-Steinmann, thanks for looking at the issue and proposing a solution. Would be good if you could create the PR. It would also be great if you could document/comment the code based on what you described above so that future enhancements could be built on top of this.

**Comment by samet-akcay** [comment]
Since PR #148 addressed this, I'm closing the issue.
