### ISSUE TITLE
export patchcore to onnx error

### ISSUE THREAD

**Issue by mrljwlm** [openvinotoolkit/anomalib#440]
RuntimeError: Exporting the operator cdist to ONNX opset version 11 is not supported

**Comment by alexriedel1** [comment]
You could replace the `torch.cdist` by a simple implementation of the euclidian distance like this one: https://discuss.pytorch.org/t/understanding-cdist-function/76296/13

```
def my_cdist(x1, x2):
    x1_norm = x1.pow(2).sum(dim=-1, keepdim=True)
    x2_norm = x2.pow(2).sum(dim=-1, keepdim=True)
    res = torch.addmm(x2_norm.transpose(-2, -1), x1, x2.transpose(-2, -1), alpha=-2).add_(x1_norm)
    res = res.clamp_min_(1e-30).sqrt_()
    return res
```
I guess the operators are all supported in onnx. 


or maybe even just: https://discuss.pytorch.org/t/efficient-distance-matrix-computation/9065/5

**Comment by ORippler** [comment]
Just a quick update from my side:

support for `torch.cdist` was added in PyTorch 1.12 by partitioning/refactorign `cdist` via supported ops in onnx (see [this PR](https://github.com/pytorch/pytorch/pull/75278), so export to onnx should work and does work.

However, the exports of all models that use gaussian blur from kornia fails in 1.12 (due to dynamic determination of kernel_size).

Side note 2:

You won't be able to convert patchcore for application on VPUs though, see [here](https://github.com/openvinotoolkit/openvino/issues/11598)

**Comment by fujikosu** [comment]
@ORippler Thanks for the info here! I tried to install pytorch 1.12 with anomalib 0.35. But pytorch version was automatically degraded to 1.11. I suspect the reason why is because that newest pytorch version is only compatible with torchvision 0.13 for now according to [this page](https://pypi.org/project/torchvision/).

torch | torchvision | python
-- | -- | --
main / nightly | main / nightly | >=3.7, <=3.10
1.11.0 | 0.12.0 | >=3.7, <=3.10
1.10.2 | 0.11.3 | >=3.6, <=3.9

anomalib has currently torchvision>=0.9.1,<=0.12.0 as dependency set in [requirements/base.txt](https://github.com/openvinotoolkit/anomalib/blob/d6951ebaaf36477bf245b17b5b6a563d35892e81/requirements/base.txt)
Because of this, I can't upgrade to pytorch 1.12. Is there any plan to cover torchvision 0.13.x (latest is 0.13.1 as of today) in dependency so that we can use torch 1.12 for onnx conversion?

**Comment by ORippler** [comment]
I just overrode those requirements manually, and this seemed to work out locally (at least for my testings with EfficientNets + onnx export of patchcore). So you could always do that.

**Comment by ashwinvaidya17** [comment]
Thanks @alexriedel1 and @ORippler for looking into this error. I am closing this issue as dependency for lightning has been increased to 0.13.0. `onnx` conversion should work fine with those using torch 1.12. But for those using lower version of torch, refer to @alexriedel1 's solution.
