### ISSUE TITLE
Using custom performance metrics

### ISSUE THREAD

**Issue by ma1rei** [openvinotoolkit/anomalib#557]
Hello, first: thanks for creating and maintaining this useful and accessible library!

I have an (beginner) issue that is more on my side (it seems like I'm not able to start a topic in the discussions section), but I hope you can help me still. I would like to extract/log other performance measures like confusion matrix values (FP/FN/TP/TN) or MCC. However, I'm unsure about how to go about this. 

I have seen that in `metric_collection_from_names `it tries to include metrics from _TorchMetrics_ package, but when I include a metric from _TorchMetrics_ in a PaDiM classification config like this

```
metrics:
  image:
    - MatthewsCorrCoef

```

the following warning is given and the metric ignored:

```
UserWarning: Incorrect constructor arguments for MatthewsCorrCoef metric from TorchMetrics package.
  warnings.warn(f"Incorrect constructor arguments for {metric_name} metric from TorchMetrics package.")
```

So this seems like the wrong approach. Can you help me understand how to include metrics other than F1 and AUROC? Thank you!

**Comment by ma1rei** [comment]
I would appreciate some insight here, as it would be a great help. Thank you!

**Comment by djdameln** [comment]
Importing metrics directly from torchmetrics without any modifications currently only works for metrics that can be constructed without passing any constructor arguments. The `MatthewsCorCoef` metric that you're trying to use requires that the `num_classes` parameter is passed when the metric is constructed. When Anomalib tries to add this metric to the collection in `metric_collection_from_names`, it fails to instantiate the class because it tries to construct it without arguments.

Unfortunately, we currently don't have a mechanism implemented to change the metric's parameters from the config file.

As a workaround, you could create your own custom metric that inherits from `MatthewsCorCoef` and specifies a default set of constructor arguments, e.g.:

```
from torchmetrics import MatthewsCorrCoef

class CustomMatthewsCorrCoef(MatthewsCorrCoef):

    def __init__(self):
        super().__init__(num_classes=2)
```
If you then add your custom metric to the list of custom anomalib metrics [here](https://github.com/openvinotoolkit/anomalib/blob/main/anomalib/utils/metrics/__init__.py#L23), it will be recognized by `metric_collection_from_names` and added to the metric collection.

**Comment by ma1rei** [comment]
This is a great help, thank you!
