### ISSUE TITLE
001_getting_started.ipynb error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [openvinotoolkit/anomalib#849]
When I ran 001_getting_started.ipynb on Google Colab, the following error occurred.

```
MODEL = "padim"  # 'padim', 'cflow', 'stfpm', 'ganomaly', 'dfkde', 'patchcore'
CONFIG_PATH = f"../../anomalib/models/{MODEL}/config.yaml"
with open(file=CONFIG_PATH, mode="r", encoding="utf-8") as file:
    print(file.read())

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-4-98a5f58a7855>](https://localhost:8080/#) in <module>
      1 MODEL = "padim"  # 'padim', 'cflow', 'stfpm', 'ganomaly', 'dfkde', 'patchcore'
      2 CONFIG_PATH = f"../../anomalib/models/{MODEL}/config.yaml"
----> 3 with open(file=CONFIG_PATH, mode="r", encoding="utf-8") as file:
      4     print(file.read())

FileNotFoundError: [Errno 2] No such file or directory: '../../anomalib/models/padim/config.yaml'
```

**Comment by samet-akcay** [comment]
Can you tell me what your current directory is ? (ie., the output of `pwd` in your notebook?)

**Comment by Ishihara-Masabumi** [comment]
The current directory is as follows:

```
!pwd
/content/anomalib
```

**Comment by stillgreyfox** [comment]
It's a relative pathing issue, and can be tricky sometimes in jupyter.

For this one

Change

`CONFIG_PATH = f"../../anomalib/models/{MODEL}/config.yaml"`

to

`CONFIG_PATH = f"./models/{MODEL}/config.yaml"`

You'll want to pay attention to other places where there's `../` used since it's trying to move out of the `anomalib/notebooks/000_getting_started/` directory

I don't think doing

!cd /content/anomalib/notebooks/000_getting_started/ will help you, but you want to have started the 001_getting_started.ipynb from the directory it's in in the git repo, vs wherever colab did it.

**Comment by samet-akcay** [comment]
PR #863 fixed this problem.

**Comment by Ishihara-Masabumi** [comment]
Thanks. It's OK.
